name: Package and Release

# Run on new tags
on:
  push:
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # secret is automatically provided to the workflow

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs

      - name: BigWigs Packager
        uses: BigWigsMods/packager@v2
        with:
          args: -p 404939 -w 26325
